title: ilkom.my.id
email: deo@ilkom.my.id
description: Tempat latihan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ilkom.my.id/"
twitter_username: deovaliandro
github_username:  sisfok

# Build settings
# theme: minima
plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
highlighter: rouge
