title: Home
email: deo@ilkom.my.id
description: Tempat latihan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ilkom.my.id/"
twitter_username: deovaliandro
github_username:  sisfok

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-toc
  - jekyll-email-protect

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true

toc:
  ordered_list: true