title: ilkom.my.id
email: deo@ilkom.my.id
description: Tempat latihan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ilkom.my.id/"
twitter_username: deovaliandro
github_username:  sisfok

# Build settings
theme: minima
plugins:
  - jekyll-feed
